### ISSUE TITLE
Issue with database table prefix

### ISSUE THREAD

**Issue by samstevens** [solspace/craft3-calendar#1]
Hi guys,

Great work on getting the beta released. I've had a chance to have a play and found a couple of small issues. 

My craft install has a "craft_" table prefix and this looks to have caused a couple of issues.

I've been able to apply a couple of hotfixes to the following files - 

`solspace/craft3-calendar/src/elementtypes/Calendar_EventElementType.php:284`
`solspace/craft3-calendar/src/Library/DatabaseHelper.php:36`
`solspace/craft3-calendar/src/Records/CalendarRecord.php:26`
`solspace/craft3-calendar/src/Services/CalendarsService.php:475`

Thanks :)

**Comment by samstevens** [comment]
Oh, and I renamed the db tables manually - so you might need to look at

`solspace/craft3-calendar/src/migrations/Install.php` 

as well :) Thanks.

**Comment by gustavs-gutmanis** [comment]
Thanks for letting us know, this will be fixed in the next version
