### ISSUE TITLE
Translations are missing

### ISSUE THREAD

**Issue by sebastian-lenz** [solspace/craft3-calendar#10]
The repository contains translations right here: https://github.com/solspace/craft3-calendar/tree/master/src/translations. However, in Craft 3 the path schema for translation files has changed (see https://github.com/craftcms/docs/blob/v3/en/changes-in-craft-3.md#static-translation-files), so currently they are not loaded/used.

**Comment by gustavs-gutmanis** [comment]
Thanks for letting us know!
This will be fixed in the upcoming version.

**Comment by kjmartens** [comment]
I just wanted to clarify that the next release (beta 5) is due today and we won't have time to finish this issue completely before the release. It will include a partial fix for this issue, but we noticed that several areas are still not translating correctly. It'll be corrected for our next release though.

**Comment by thaoms** [comment]
Is this fixed yet?
I placed the translation file in translations/nl/calendar.php
But the months are still in english.

**Comment by kjmartens** [comment]
It should all be correct now... where specifically are you seeing this issue? :)

**Comment by thaoms** [comment]
I'm outputting some months in my site's footer.

```
{% set footerMonth = craft.calendar.month({
    date: "today"
}) %}
````

````
{% for dateObj in footerMonth.dateRange(0, 6) %}
<li><a class="text-uppercase" href="{{ siteUrl }}agenda/{{ dateObj.format('Y/m/d') }}">{{ dateObj.format('F Y') }}</a></li>
{% endfor %}
````

**Comment by thaoms** [comment]
This can be closed.
By using the |date filter instead of .format().
