### ISSUE TITLE
Custom Title format

### ISSUE THREAD

**Issue by stianmandarin** [solspace/craft3-calendar#11]
Hey,
really sorry to bring this up again like this https://github.com/solspace/craft3-calendar/issues/3 but I've been in contact with you for a few weeks since I have a client meeting coming up in just two days now.

Is there any chance this particular feature will be fixed by then?

And am I correct in thinking that a Users field will be able to take the place of the Title field, thus effectively making usernames into event titles? Or won't that work regardless?

**Comment by kjmartens** [comment]
Sorry, we did half-fix #3 in a recent release, but for general Event creating, and not for Quick Creating. I've reopened the old issue and will close this one. We'll have another update out today that will include a fix for this. :)
