### ISSUE TITLE
Custom fields for events already implemented?

### ISSUE THREAD

**Issue by 24HOURSMEDIA** [solspace/craft3-calendar#13]
Hi,

Are custom fields for events already implemented like the docs for Craft 2 mention?
I cannot seem to add a description field for instance to an event.

BTW the plugin looks great!

**Comment by kjmartens** [comment]
HI @24HOURSMEDIA, yes, custom fields should be working for Calendar 2. If they aren't for you, can you elaborate on the issue you're experiencing? :)

**Comment by 24HOURSMEDIA** [comment]
Hi, maybe am missing something, but I can't find where I can set up the field layout (i.e. add fields).
I am using Calendar 2.0.0-beta.6 from the plugin store against Craft 3 RC15

**Comment by 24HOURSMEDIA** [comment]
Oh I see now.. it is specific to a calendar on for example admin/calendar/calendars/default
Thanks for the confirmation that it should be there, found it :)

**Comment by kjmartens** [comment]
You setup field layouts / add fields directly inside each calendar. So you would go to Calendar -> Calendars -> Click title of a calendar and scroll to bottom of page to see a similar field layout editor as used for sections. :)
