### ISSUE TITLE
Multi-site index pages with calendar for only one site

### ISSUE THREAD

**Issue by davist11** [solspace/craft3-calendar#15]
We have a craft install setup with 5 sites, but there is only one calendar, which is only enabled for one site.

![screen shot 2018-04-02 at 4 04 06 pm](https://user-images.githubusercontent.com/199985/38213512-7dda663c-368f-11e8-9d73-2977d77c7319.png)

When you view the events index, `admin/calendar/events`, it shows multiple sites in the dropdown.

![screen shot 2018-04-02 at 4 04 26 pm](https://user-images.githubusercontent.com/199985/38213541-9cf42968-368f-11e8-9dc5-ca59856aaf87.png)

Seems like this dropdown shouldn't be visible since there are events enabled for only one site.

Craft CMS 3.0.0-RC17.1
Calendar 2.0.0-beta.7

**Comment by kjmartens** [comment]
I'm not so sure this is a bug exactly. When I view the Craft Entries area for example (`admin/admin/entries`), it still presents me a list of all available sites, even though I only have 1 section and it's set to only be enabled for 1 site.

**Comment by davist11** [comment]
True, good point.
