### ISSUE TITLE
Undefined class constant 'Client' after update to Craft 3.0.0 GA

### ISSUE THREAD

**Issue by magnessjo** [solspace/craft3-calendar#16]
In the latest version of Calendar (beta 8), an error is thrown due to Craft switching it edition types.  I believe the types are now Solo and Pro.  Client appears to have been removed.  

To reproduce: 

  Download craft 3.0.0 (not RC versions) and calendar beta 8.

**Comment by kjmartens** [comment]
Thanks, we're pushing out an update shortly. It seems like they last minute removed the Client edition from Craft 3 for `3.0.0`. Until the update is available, to get around this, you can update `Client` to `Pro`. :)

**Comment by magnessjo** [comment]
Thank you @kjmartens,

  I modified the calendar core at the time, but reverted and did a composer update for beta 9 and it is working fine.
