### ISSUE TITLE
Setting unknown property: Solspace\Calendar\Elements\Db\EventQuery::dateRangeStart

### ISSUE THREAD

**Issue by thaoms** [solspace/craft3-calendar#18]
I'm getting an error when fetching events with dateRangeStart.

```
{% set events = craft.calendar.events({
	id: events,
	order: 'startDate',
	loadOccurrences: false,
	dateRangeStart: now
}) %}
```

**Comment by thaoms** [comment]
Nevermind, I found that the docs are outdated, found the solution in the demo templates.

**Comment by kjmartens** [comment]
@thaoms Sorry for the trouble... we'll have new docs for Calendar 2 soon :)
