### ISSUE TITLE
[BUG] "Title Field Label" overwrite not working

### ISSUE THREAD

**Issue by Antimated** [solspace/craft3-calendar#202]
**Describe the bug or issue you're experiencing**
Overwriting the `Title Field Label` is not reflected when creating events

**Calendar title setting**
![Screenshot 2023-01-31 at 14 00 21](https://user-images.githubusercontent.com/2869409/215766673-82860dcc-0319-4516-9ec6-87656aa84ba7.png)

**Title setting not changing**
![Screenshot 2023-01-31 at 14 01 11](https://user-images.githubusercontent.com/2869409/215766839-97cee532-7f7a-4b81-a031-c1690c5983b2.png)

**Steps to reproduce**

1. Create calendar
2. Set `Title Field Label` to something different
3. Add new event in said calendar
4. Notice how the title field still is called `Title`

**Expected behavior**
`Title` field should be renamed to `Episode nr.`

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.6.1
- Calendar Version: 4.0.4
- Calendar Edition: Pro
- Fresh Install or Upgrade: Fresh

**Comment by kjmartens** [comment]
Sorry for the trouble @Antimated. We'll get this fixed soon. 🙂

**Comment by kjmartens** [comment]
This has now been resolved in Calendar 4.0.5. 🙂
