### ISSUE TITLE
4.0.4 Backend Ordering Issues

### ISSUE THREAD

**Issue by phillipsandoveracademy** [solspace/craft3-calendar#204]
**Describe the bug or issue you're experiencing**

Upon upgrading from 4.0.2 -> 4.0.4, unable to order by Start Date or other views on the backend. Post Date is the only field that appears to work. 

**Steps to reproduce**

1. Upgrade 4.0.2 -> 4.0.4
2. Test backend ordering views

**Expected behavior**

Able to order by different fields in the view.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.6.1
- Calendar Version: 4.0.4
- Calendar Edition: Pro
- Fresh Install or Upgrade:

**Additional context**

**Production running 4.0.2**
![Screen Shot 2023-01-31 at 2 25 09 PM](https://user-images.githubusercontent.com/11964584/215863035-0375e350-f2b0-47d8-8fa5-a80b9506e4ea.png)

**Local Development 4.0.4**
![Screen Shot 2023-01-31 at 2 24 22 PM](https://user-images.githubusercontent.com/11964584/215863164-8d9e0608-ae50-4db4-bfe6-4cf376b3878c.png)

On another site, the ordering on the backend appears to be fine and working as expected. I don't know what the difference is. On this site, I did reinstall and refresh with a clean db backup with no luck.

**Comment by kjmartens** [comment]
Hi @phillipsandoveracademy,

Oddly I cannot duplicate this one. We will check into the other issues and address them shortly, so perhaps the fix that we apply for the front end ordering will fix this for you as well. We'll leave this issue open until you can confirm in Calendar 4.0.5 (next version). 🙂

**Comment by kjmartens** [comment]
I believe this should now be resolved in Calendar 4.0.5. Let me know if the issue persists. 🙂
