### ISSUE TITLE
4.0.4 Field Layout Issues

### ISSUE THREAD

**Issue by phillipsandoveracademy** [solspace/craft3-calendar#205]
**Describe the bug or issue you're experiencing**

A calendar event is missing the field layout tabs. Everything is on one page.

**Steps to reproduce**

1. Upgrade Calendar 4.0.2 -> 4.0.4 
2. View calendar event

**Expected behavior**

The field layout defined in the calendar shows the field layout tabs as expected throughout Craft CMS.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.6.1
- Calendar Version: 4.0.4
- Calendar Edition: Pro
- Fresh Install or Upgrade:

**Additional context**

**Calendar Field Layout defined**
![screenshot-athletics4 ddev site-2023 02 01-09_58_59](https://user-images.githubusercontent.com/11964584/216080100-9f17b004-08ad-4962-8ddd-8616636a129f.png)

**Calendar Event page**
![screenshot-athletics4 ddev site-2023 02 01-09_59_37](https://user-images.githubusercontent.com/11964584/216080223-7cbf9130-9109-4f75-bb7e-49ec978ed569.png)

**Comment by kjmartens** [comment]
Hi @phillipsandoveracademy,

I'm very sorry for the trouble caused. We'll address this issue shortly. 🙂

**Comment by kjmartens** [comment]
This has now been resolved in Calendar 4.0.5. 🙂
