### ISSUE TITLE
Front End Submit - Multi Day

### ISSUE THREAD

**Issue by NathanBate** [solspace/craft3-calendar#209]
Your docs here:
https://docs.solspace.com/craft/calendar/v4/templating-extras/events-front-end.html#example-code-from-demo-templates

Don't give any information about making a multi-day submission work. They imply that a multi-day submission will work because it has a start date and an end date. 

However, this will not work unless this hidden input is included.
`<input type="hidden" name="calendarEvent[multiDay]" value="1" />`

This took me a while to figure out, and I think it is worth updating your docs.

Thanks for a great plugin.

**Comment by kjmartens** [comment]
Sorry for this @NathanBate,

We'll get the docs updated shortly. In the meantime, this is a better approach: 🙂 

``` twig
<input type="hidden"
       id="multiDay"
       name="calendarEvent[multiDay]"
       value="{{ event.isMultiDay }}"
       data-toggle-button
/>
```

**Comment by laurabennett** [comment]
This is definitely confusing. Would be nice if it worked the same as the All Day toggle.
