### ISSUE TITLE
Disabled events disappear from events list

### ISSUE THREAD

**Issue by TUSAB-web** [solspace/craft3-calendar#220]
**Describe the bug or issue you're experiencing**

Disabled events disappear and are inaccessible from either the events list or the calendar.

**Steps to reproduce**

1. Create an event
2. Save the event, confirm it is on calendar
3. Set the event to disabled.
4. Open the “events” view and select “disabled” events. There is nothing there.

**Expected behavior**

Disabled events should appear in the list. I also turned on the "Include Disabled Events in Month/Week/Day views” option.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.4.2
- Calendar Version: 4.0.7
- Calendar Edition: LITE
- Fresh Install or Upgrade: upgrade

**Additional context**

Disabled entries in other parts of Craft appear normally... it’s just in the Calendar plugin.

**Comment by murphy1484** [comment]
We have the same problem.
Issue was introduced in version 4.0.7. 
Downgraded to 4.0.6 for now.

**Comment by kjmartens** [comment]
Hi @TUSAB-web and @murphy1484,

Sorry for the trouble you're experiencing. I am able to reproduce this on my end too (only when the Craft install has a single site). We'll get it fixed early next week. 🙂

**Comment by TUSAB-web** [comment]
I wanted to check in on this. Do we know when the fix will be pushed out?

**Comment by kjmartens** [comment]
Sorry for the delay. This should now be fixed in Calendar 4.0.8+. 🙂
