### ISSUE TITLE
Saving an entry throws an Unauthorized Exception when website status is deactivated but user has no permissions

### ISSUE THREAD

**Issue by superextinct** [solspace/craft3-calendar#222]
**Describe the bug or issue you're experiencing**
When trying to save a calendar entry, a `ForbiddenHttpException` is thrown: 
> User not permitted to edit the statuses for all the submitted site IDs

This is expected, when a user does not have permission to edit the associated site. However, this should not occur, when the status for website without permissions is deactivated:

<img width="374" alt="Bildschirm­foto 2023-03-29 um 12 40 49" src="https://user-images.githubusercontent.com/41620375/228509641-045d66eb-a9aa-4149-8d8b-f76d7c4609ca.png">

Here, the user has permission to edit site A, but not site B, C, or D. In this case, the entry should be saved successfully.

The error gets thrown here:

```php
// packages/plugin/src/Controllers/EventsController.php

protected function enabledForSiteValue(): array|bool|null
{
    $enabledForSite = $this->request->getBodyParam('enabledForSite');
    if (is_array($enabledForSite)) {
        // Make sure they are allowed to edit all of the posted site IDs
        $editableSiteIds = \Craft::$app->getSites()->getEditableSiteIds();

        if (array_diff(array_keys($enabledForSite), $editableSiteIds)) {
            throw new ForbiddenHttpException('User not permitted to edit the statuses for all the submitted site IDs');
        }
    }
    return $enabledForSite;
}
```

In this instance, `$enabledForSite` contains '1' for every activated website status (here only one, for site A) – but it also contains an empty string for every other website, which should be deactivated. Since the user does not have permission to edit sites B, C and D, the difference between `$enabledForSite` and `$editableSiteIds` is now 3 empty strings – hence the forbidden exception gets thrown.

**Steps to reproduce**

1. Setup a calendar which is enabled for multiple sites.
2. Switch to a user which does not have permission to edit one of these sites.
3. Try to create or edit a new calendar entry which is enabled only for the sites that user can edit.

**Expected behavior**
Saving an entry should only throw an error, when a website status is enabled, for which the editing user does not have permission to edit. In this specific case, saving should be allowed. The `$enabledForSite` array should filter out sites with no status:

```php
$enabledForSite = $this->request->getBodyParam('enabledForSite');
if (is_array($enabledForSite)) {
    // Make sure they are allowed to edit all of the posted site IDs
    $editableSiteIds = \Craft::$app->getSites()->getEditableSiteIds();
    // Only check sites, for which the entry is enabled
    $enabledForSite = array_filter($enabledForSite);
 // …
```

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 4.4.5
- Calendar Version: 4.0.8
- Calendar Edition: Pro
- Fresh Install or Upgrade: Upgrade from Craft 3

**Comment by kjmartens** [comment]
This is now fixed in Calendar 4.0.9. 🙂
