### ISSUE TITLE
Documentation example code has a bug on it

### ISSUE THREAD

**Issue by webrgp** [solspace/craft3-calendar#232]
In this page:

https://docs.solspace.com/craft/calendar/v4/templates/queries/export/#usage-in-templates

This example:

```twig
{%- set events = craft.calendar.events({
  calendarId: [1, 3, 5],
  rangeStart: "1 year ago",
  rangeEnd: "5 years",
  loadOccurrences: false
})) -%}

{%- header "Content-Type: application/octet-stream" -%}
{%- header "Content-Transfer-Encoding: binary" -%}

{{- craft.calendar.export(events) -}}
```

The `craft.calendar.events` has an extra closing parentheses on it.

**Comment by kjmartens** [comment]
Thanks for reporting this @webrgp. We'll correct that shortly. 🙂

**Comment by webrgp** [comment]
No problem, I would have fixed myself, but I could't find a repo for the docs...
