### ISSUE TITLE
Saving a calendar moves recurring events into the future.

### ISSUE THREAD

**Issue by ctruett** [solspace/craft3-calendar#251]
Unfortunately, this issue is still happening on 4.0.11.

Brand new calendar, brand new events.

Created events, changed a setting (any setting, as far as I can tell, but most recently it was switching to a fixed time zone instead of a floating one) on the corresponding calendar page and it pushes all events six months into the future. 

_Originally posted by @ctruett in https://github.com/solspace/craft-calendar/issues/236#issuecomment-1890483750_

**Comment by ctruett** [comment]
I've also noticed that sometimes just saving a weekly recurring event pushes it a year into the future.

**Comment by kjmartens** [comment]
Sorry for the delay and the trouble.

This should be resolved now in Calendar 4.0.12+. 🙂
