### ISSUE TITLE
URGENT: Selected Dates are moved one day back upon save on frontend forms

### ISSUE THREAD

**Issue by outline4** [solspace/craft3-calendar#261]
**Describe the bug or issue you're experiencing**

When saving an event in the frontend the date that is shown by javascript and the date that is saved, is moved one day back: 

**Steps to reproduce**

1. I choose a date in the datepicker and the following is displayed: 

Fr. 29. March 2024

<img width="338" alt="Bildschirmfoto 2024-03-04 um 17 36 12" src="https://github.com/solspace/craft-calendar/assets/145828/4c1ca43a-2b0d-4872-9a71-d93cbe3a2b5d">

When inspecting I see the following: 

<img width="538" alt="Bildschirmfoto 2024-03-04 um 17 36 57" src="https://github.com/solspace/craft-calendar/assets/145828/8f52f8b5-6272-4fdf-afae-7105a62bd36e">

2. I save the entry and the date moves one day back: 

Thu 28. March 2024

<img width="338" alt="Bildschirmfoto 2024-03-04 um 17 37 12" src="https://github.com/solspace/craft-calendar/assets/145828/059436e5-5d9f-4ca5-b68f-dc66bb626f52">

**Expected behavior**

Dates shouldn't move...

**This is the code concerned**: 

	<div class="form-group row" data-repeats data-show-for="select_dates">
		<label class="col-sm-2 col-form-label">
			{{ "On select dates"|t }}
		</label>
		<div class="col-sm-2">
			<input type="text"
				 	name="calendarEvent[selectDate]"
				 	class="form-control date-picker select-date-picker"
				 	placeholder="{{ dateFormat }}" />
		</div>
	</div>
	
	<div class="form-group row select-dates-list" data-repeats data-show-for="select_dates">
		{% for selectDate in event.selectDatesAsDates %}
			<div class="col-12 col-sm-10 offset-sm-2">
				<input type="hidden" name="calendarEvent[selectDates][]" value="{{ selectDate.toDateTimeString }}" />
				<a href="javascript:;"
				 	class="remove-select-date"
				 	style="color: darkred; text-decoration: none; position: relative; top: 1px;">
					<span class="far fa-times-circle"></span>
				</a>
				{{ selectDate.format('D d. F Y') }}
			</div>
		{% endfor %}
	</div>

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.5.13
- Calendar Version: 4.0.11
- Calendar Edition: Pro
- Fresh Install or Upgrade: Fresh

**Additional context**

Please: this is urgent... It's on a live site!

**Comment by outline4** [comment]
BTW: this happens on the demo site as well. 

Only with selected dates! 

This is a serious problem for us!

**Comment by kjmartens** [comment]
Sorry for the delay @outline4,

I played around with this on my end and I wasn't able to duplicate the issue at all. I tried a variety of things, but it always works correctly for me.

However, once I switched the event to be an ALL DAY event, after saving the event a couple of times, it then seemed to push the date forward by 1 day (opposite of what you are noticing), and only affected a couple of the later dates... not all of them.

Just to confirm, are your events set to "All Day" as well? If not, what kind of times do you have for them? And does this issue affect ALL events using Select Dates feature? 🙂

**Comment by outline4** [comment]
Hi, at the moment it happens on all selected days entries and I could swear it didnt do it a while ago… but I only tested it with fake days… 

maybe it has to do with timelight saving? 

did you try it in a different language and different timezone? 

it happens on the demo templates as well…
should I send you a login?

**Comment by seandelaney** [comment]
@outline4 

I see you are using v4.0.11. 

Have you tested v4.0.12 that has a fix for a similar issue where dates jump?

https://github.com/solspace/craft-calendar/blob/v4.0.12/CHANGELOG.md#4012---2024-03-07

**Comment by seandelaney** [comment]
@outline4 I've replicated the bug and fixed it. PR coming soon.

**Comment by outline4** [comment]
Oh thank you so much! 

I've just installed v4.0.12 and can confirm that the bug still exists in this version.  

This time it's only on the first save that all *selected* dates are moved back one day. After the first save, only one date is moved back one day. Usually the last date, but not always. 

Glad you identified the bug, since this was bugging us quite a lot. 

Cheers  
Stefan

**Comment by outline4** [comment]
Btw: I've applied the change manually and can confirm that it seems to work perfectly... None of the above things happen anymore! 

I am glad and thankful you found this bug!
