### ISSUE TITLE
can't change .format to |date in event.selectDatesAsDates 

### ISSUE THREAD

**Issue by outline4** [solspace/craft3-calendar#263]
**Describe the bug or issue you're experiencing**

When changing `.format('')` to `|date('')` it will shift the dates one day.  
I need to change it to a date filter in order that the dates will display in german. 

**Steps to reproduce**

In the frontend form I cannot change the date to a localized date: 

	{% for selectDate in event.selectDatesAsDates %}
		<div class="col-12 col-sm-10 offset-sm-2">
			<input type="hidden" name="calendarEvent[selectDates][]" value="{{ selectDate.toDateTimeString }}" />
			<a href="javascript:;"
				 class="remove-select-date"
				 style="color: darkred; text-decoration: none; position: relative; top: 1px;">
				<span class="far fa-times-circle"></span>
			</a>
			{{ selectDate.format('D. d. F Y') }}
		</div>
	{% endfor %}

If I change `{{ selectDate.format('D. d. F Y') }}` to `{{ selectDate|date('D d. F Y') }}` it will shift the dates one day. 

How can I achieve what I want to do? 

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.5.13
- Calendar Version: 4.0.11
- Calendar Edition: PRO
- Fresh Install or Upgrade: Fresh

**Comment by kjmartens** [comment]
Hi @outline4,

Sorry again for the delays...

This is a limitation that we worked around in other areas where you can change `event.startDate.format("l, F j, Y g:ia")` to `event.startDateLocalized|date("l, F j, Y g:ia")` and it will resolve the issue. However, it seems the special `Localized` version is not available for `selectDate`.

I've noted this to see if we can get a quick update for this done. 🙂

**Comment by seandelaney** [comment]
Once PR is approved, merged and new version released, you will be able to do the following:

```
{% for selectDate in event.selectDatesAsDates %}
   {{ selectDate.format('l, F j, Y') }}
{% endfor %}

{% for selectDate in event.selectDatesAsDatesLocalized %}
   {{ selectDate|date('l, F j, Y') }}
{% endfor %}

{% for exception in event.exceptions %}
   {{ exception.date.format('l, F j, Y') }}
{% endfor %}

{% for exception in event.exceptionsLocalized %}
   {{ exception.date|date('l, F j, Y') }}
{% endfor %}
```

**Comment by outline4** [comment]
Hi, I finally got around to trying it. 

	<div class="form-group row select-dates-list" data-repeats data-show-for="select_dates">

		{# for localization: see https://github.com/solspace/craft-calendar/issues/263#issuecomment-2037177668 #}
		{% for selectDate in event.selectDatesAsDatesLocalized %}
			<div class="col-12 col-sm-10 offset-sm-2">
				<input type="hidden" name="calendarEvent[selectDates][]" value="{{ selectDate.toDateTimeString }}" />{# {{ selectDate.toDateTimeString }} #}
				<a href="javascript:;"
					 class="remove-select-date"
					 style="color: darkred; text-decoration: none; position: relative; top: 1px;">
					<span class="far fa-times-circle"></span>
				</a>
				{{ selectDate|date('D d. F Y') }}
			</div>
		{% endfor %}
	</div>

It works, once it's saved. But choosing the dates is still in english. 


I think this is the js involved: 

	var $selectDate = $(".select-date-picker");
	$selectDate.datepicker("option", "onSelect", function (dateText) {
		var date = new moment(dateText, convertDateFormatToMomentFormat(dateFormat));

		var $div = $("<div class=\"col-12 col-sm-10 offset-sm-2\" />");
		var $input = $("<input />");
		$input
		.attr("type", "hidden")
		.attr("name", "calendarEvent[selectDates][]")
		.val(date.format("YYYY-MM-DD"));

		$div
		.append("<a href=\"javascript:;\" class=\"remove-select-date\" style=\"color: darkred; text-decoration: none; position: relative; top: 1px;\"><span class=\"far fa-times-circle\"></span></a>")
		.append(" " + date.format("dd. D. MMMM YYYY"))
		.append($input);

		$(".select-dates-list").append($div);
		$selectDate.val("");
	});
	});

Do you know how to handle this so the date picker and the chosen dates are in german?
