### ISSUE TITLE
Custom Exporters for Calendar Events

### ISSUE THREAD

**Issue by sadmachine** [solspace/craft3-calendar#266]
### Discussed in https://github.com/solspace/craft-calendar/discussions/265

<div type='discussions-op-text'>

<sup>Originally posted by **sadmachine** March 20, 2024</sup>
Was hoping for some help regarding exporting calendar events from the solspace/craft-calendar plugin. For standard craft entries, you can define and register custom exporters that will show up in the "Export Type" list like below:
![image](https://github.com/solspace/craft-calendar/assets/9452483/e605ab6d-4660-407b-9f5f-00505adcf630)

However, when I go to export events from the Calendar plugin, those custom exporters do not show up:
![image](https://github.com/solspace/craft-calendar/assets/9452483/ec7ba545-3a7e-4bf5-81b2-721a5f725011)

Is there anyway to define custom exporters for these events? The standard format of the export is not workable and we would like to define a custom export to only grab the information we need in a format that is more workable.
</div>

**Comment by seandelaney** [comment]
Answered in https://github.com/solspace/craft-calendar/discussions/265
