### ISSUE TITLE
After updating to version 5.0 from 4.0.11 receiving a column not found error.

### ISSUE THREAD

**Issue by a-am** [solspace/craft3-calendar#268]
Updating Calendar to version 5.0 from 4.0.11 on Craft CMS 4.8.6, whenever I try to access the Calendar or Event List I get a 500 error in Javascript or when trying to edit an entry with an events input we get a `Column not found: 1054 Unknown column 'craft_calendar_events.authorId' in 'on clause' in /vendor/yiisoft/yii2/db/Command.php:1302` error. 

If trying to resave events from the command line using `craft  calendar/events/resave` I get the same error. 

**Steps to reproduce**

1. Update Calendar to 5.0 from Calendar 4.0.11 in Craft CMS 4.8.6
2. Attempt to view calendar, event list,  or an entry with an events input

**Expected behavior**
Our expectation is when accessing the calendar we would not see these errors.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.6
- Calendar Version: 5.0
- Calendar Edition: Pro
- Fresh Install or Upgrade: Upgrade

I can confirm that the authorId column is in the table.  When trying to debug in the EventQuery.php file I tried to comment out all the authorId reference.  However the same error occurred for the column `calendarId`. 
We have tried this on several sites same versions of craft. 

#### Included Error
[solspace_calendar_error.txt](https://github.com/solspace/craft-calendar/files/14797299/solspace_calendar_error.txt)

**Comment by johnnymueller** [comment]
I'm experiencing the same issue. Same Craft (4.8.6) and Calendar Pro (4.0.11 -> 5.0) version. I'm also getting the authorId error when trying to view any front end page:
<img width="1237" alt="Screenshot 2024-04-01 at 3 37 24 PM" src="https://github.com/solspace/craft-calendar/assets/369241/5616517c-c8d2-469b-a975-d2cde385fe05">

**Comment by TUSAB-web** [comment]
I am experiencing the same error as well

**Comment by seandelaney** [comment]
@a-am @johnnymueller @TUSAB-web 

I was unable to replicate the issue last week when I briefly looked at this.

I'm back on it today but I am still struggling to replicate.

Can I please have some more info on your Calendar setups? Types of users, permissions etc. Anything specific like this would help.

Thanks

**Comment by a-am** [comment]
@seandelaney here are some other plugins we are using along side Calendar,
- Redactor
- Typed link field
- Neo
- Formie
- Seomatic/Retour/Vite/Minify
- Position Fieldtype

We have tried both updating from the command line and the CP with equal results. I have had the same results on Production and Local environments both using PHP 8.2. However, these may not be apart of the issue because just trying to access the calendar gives 500 errors and events are not loaded into the calendar.

**Comment by seandelaney** [comment]
@a-am 

Getting 500 errors does not sound right at all! 

Can you check if the migration script ran?

Also, what does your Calendar settings look like before you upgraded to Calendar 5? Keen to find out if you had any field layouts, user permissions etc?

**Comment by a-am** [comment]
@seandelaney 
- I can confirm the migration script ran: `m240319_132700_UpdateElements`. 
- User permission are all open. 
- As far as fields several text fields, one assets field, and one NEO field, on all our Calendars.
- ICS is turned on for some not all
- Have not changed any of the standard Calendar settings or Global Calendar settings.

Here is the error message from the javascript call to get monthly calendar events in the CP
 `"error": "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'craft_calendar_events.rrule' in 'where clause'\nThe SQL being executed was: SELECT elements.id\nFROM (SELECT elements.id AS elementsId, elements_sites.id AS elementsSitesId, content.id AS contentId\nFROM craft_elements elements\nINNER JOIN craft_calendar_events calendar_events ON calendar_events.id = elements.id\nINNER JOIN craft_elements_sites elements_sites ON elements_sites.elementId = elements.id\nINNER JOIN craft_content content ON content.elementId = elements.id\nINNER JOIN craft_calendar_calendars ON craft_calendar_calendars.id = craft_calendar_events.calendarId\nLEFT JOIN craft_users ON craft_users.id = craft_calendar_events.authorId\nWHERE ((craft_calendar_events.rrule IS NULL AND craft_calendar_events.endDate >= '2024-04-01 00:00:00')\n                OR (craft_calendar_events.rrule IS NOT NULL AND craft_calendar_events.until IS NOT NULL AND craft_calendar_events.until >= '2024-04-01 00:00:00')\n                OR (craft_calendar_events.rrule IS NOT NULL AND craft_calendar_events.until IS NULL)\n                OR (craft_calendar_events.freq = 'SELECT_DATES')) AND (craft_calendar_events.startDate <= '2024-05-06 23:59:59' OR craft_calendar_events.freq = 'SELECT_DATES') AND (elements.archived=FALSE) AND (elements.dateDeleted IS NULL) AND (elements.draftId IS NULL) AND (elements.revisionId IS NULL)\nORDER BY calendar_events.startDate) subquery\nINNER JOIN craft_elements elements ON elements.id = subquery.elementsId\nINNER JOIN craft_elements_sites elements_sites ON elements_sites.id = subquery.elementsSitesId\nINNER JOIN craft_calendar_events calendar_events ON calendar_events.id = subquery.elementsId\nINNER JOIN craft_content content ON content.id = subquery.contentId\nINNER JOIN craft_calendar_calendars ON craft_calendar_calendars.id = craft_calendar_events.calendarId\nLEFT JOIN craft_users ON craft_users.id = craft_calendar_events.authorId\nORDER BY calendar_events.startDate",`

**Comment by seandelaney** [comment]
@a-am 

I'm now running Craft 4.8.6 on PHP 8.2. Calendar 5. Still not getting any errors.

You also seem to be getting different errors too. `authorId` and now `rrule`. 

Any chance you could send me a DB backup with your calendar tables?  Remove all sensitive data.

sean@solspace.com

What MySQL version are you running?



@TUSAB-web @johnnymueller 

Are you guys also experiencing the same errors or different errors?

Are you also running Craft 4 with PHP 8.2 ?

What MySQL version are you running?

**Comment by seandelaney** [comment]
@a-am @johnnymueller @TUSAB-web 

I'll have a PR coming soon. I've improved some subqueries to better support table prefixes - the aliases in some of the errors  posted above looked wrong. Still cannot replicate an error locally. Very weird. Tested MySQL, Postgres, PHP 8.0, PHP 8.2, Table prefixes and table no prefixes. The worst bugs are the ones you cannot replicate easily.

**Comment by a-am** [comment]
Thank you, I will give the update a go when posted and let you know. Sorry I don't have more information I know it is frustrating when you can't replicate.

**Comment by kmmartinez** [comment]
Just wanted to note I am receiving the same error as well. I've tried it on several different sites in the last week.

**Comment by kjmartens** [comment]
I'm very sorry for the trouble caused by this issue. We've just released Calendar 5.0.1 now. Can you try that out and see if it resolves the issue? 🙂

**Comment by a-am** [comment]
@kjmartens The update appears to have fixed the issue.  Thank you!

**Comment by kjmartens** [comment]
Thank you for confirming @a-am!

**Comment by TUSAB-web** [comment]
The update fixed the issue for me as well. Thanks!
