### ISSUE TITLE
Infinite redirects on primary Calendar nav

### ISSUE THREAD

**Issue by jrrdnx** [solspace/craft3-calendar#278]
Clicking the main "Calendar" link in the sidebar nav causes an infinite redirect. No issues accessing any of the child pages (Month, Week, Day, Events, Calendars, or Settings).

![Screenshot 2024-04-15 at 07 01 47-2](https://github.com/solspace/craft-calendar/assets/4584671/ffc141f6-66cc-4530-85cc-0e7e2ead7f76)

Additional content: We have our control panel set up on a subdomain, so not sure if that is having any effect. It's only the primary `/calendar` page that has the redirect.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.9
- Calendar Version: 5.0.3
- Calendar Edition: both Lite and Pro
- Fresh Install or Upgrade: Fresh Install

**Comment by kjmartens** [comment]
Hi @jrrdnx,

Is this still happening for you? I can't duplicate this issue and I haven't heard of anyone reporting this before.

What do you have set for the **Default View** setting in Calendar settings? (Maybe also reset it and save for good measure). 🙂 

Other than that, perhaps you have some sort of rewrite rule that is conflicting in some say?

**Comment by jrrdnx** [comment]
It was. Double-checked our `calendar.php` config file and saw that the `defaultView` setting was accidentally set to an empty string. Fixed that and we're good to go, thanks!
