### ISSUE TITLE
Several links in the Key Features table result in 404 pages

### ISSUE THREAD

**Issue by jrrdnx** [solspace/craft3-calendar#279]
Several of the links in the Key Features table are resulting in 404 pages. So far I've noticed "[ICS exporting](http://docs.solspace.com/craft/calendar/v4/template-functions/calendar.export.html)", "[Front end event creation](http://docs.solspace.com/craft/calendar/v4/templating-extras/events-front-end.html)", and "[Show events by months, weeks & days](http://docs.solspace.com/craft/calendar/v4/template-functions/calendar.month.html)" but there may be others.

Also noted that these are all still pointing to the documentation for v4 instead of v5.

**Comment by kjmartens** [comment]
Thanks for bringing this to our attention, @jrrdnx. I have fixed these now. 🙂
