### ISSUE TITLE
Custom "Title Format" not working

### ISSUE THREAD

**Issue by stianmandarin** [solspace/craft3-calendar#3]
I'm adding events through the Craft CP, and I'm trying to replace the default title field with a custom field as described in the instruction `{fieldHandle}`

In my case the custom field is a Users field. Is this possible? I've tried with a plain text field as well, but that doesn't work either. It still just says "Title" and whatever I enter there, I get `Could not save event` trying to save.

<img width="358" alt="screen shot 2018-03-12 at 13 51 07" src="https://user-images.githubusercontent.com/23015690/37284603-75486760-25fc-11e8-987a-507b65ab13a0.png">

**Comment by gustavs-gutmanis** [comment]
This will be fixed in the upcoming version. Thanks for letting us know!

**Comment by stianmandarin** [comment]
I'm still not getting this. See video: [https://drive.google.com/open?id=1APioPb7EB-vALw60VVdDYbb7i7IEq9pE](https://drive.google.com/open?id=1APioPb7EB-vALw60VVdDYbb7i7IEq9pE)

Or have I misunderstood, and this won't work with a Users field regardless?

Thanks!
