### ISSUE TITLE
Neo fields are not being copied when saving event as new event

### ISSUE THREAD

**Issue by luke-nehemedia** [solspace/craft3-calendar#301]
My client likes the feature to duplicate events. They do this by using the "save as new event" option while editing an event. Until recently, this worked perfectly fine. However, now they reported that the content of a Neo field is not being copied. 

I am not sure whether this is a Neo-related issue or a calendar-issue.

**Steps to reproduce**
1. Edit an event that contains a Neo-field with content.
2. Use the "save as new event" button 
3. Check whether the content of the Neo-field has been copied

**Expected behavior**
I expected the new event to be a 1:1 copy of the original one.

**Craft & Plugin Info:**
- Craft Version: Craft Pro 4.10.5
- Calendar Version: 5.0.6
- Calendar Edition:Pro
- Fresh Install or Upgrade: no

**Comment by kjmartens** [comment]
Sorry for the delay, @luke-nehemedia.

I am not sure why this might have stopped working. Do you have any idea about when this happened (e.g. upgrade from Calendar 4.x, update of Neo, etc)?

In the meantime, I have logged this for a developer to check into soon.
