### ISSUE TITLE
Events broken after Craft 4-5 upgrade ("Argument #2 ($title) must be of type string")

### ISSUE THREAD

**Issue by btbunze** [solspace/craft3-calendar#302]
**Describe the bug or issue you're experiencing**

After upgrading my site from Craft 4 (4.10.5) to Craft 5 (5.2.6), existing calendar events seem to be broken. On the Calendar plugin's Events tab, the events listed are shown as "Event #" instead of their title (e.g. "Event 1"), and when I click into an event in that view, Craft crashes and the following error is shown in the browser:

`Solspace\Calendar\Controllers\EventsController::renderEditForm(): Argument #2 ($title) must be of type string, null given, called in /var/www/html/vendor/solspace/craft-calendar/packages/plugin/src/Controllers/EventsController.php on line 180`

The upgrade from Craft 4-5 itself doesn't run into any issues, and the calendar configuration stays the same (including event fields). Attempting to retrieve the events via graphql results in the following output:

```
...
"events": [
  {
    "title": null,
    "postDate": "2021-07-09 13:50:00"
  },
  {
    "title": null,
    "postDate": "2021-09-14 10:57:00"
  },
  ...
]
...
```

**Steps to reproduce**

1. Create new craft 4 project with ddev
2. Add calendar plugin from plugin store
3. Create an event
4. Follow Craft 4-5 upgrade steps

**Expected behavior**

After Craft 4-5 upgrade, event titles are visible in the "Events" tab of the admin panel, an edit form is shown when an event is clicked, and event data (for all existing fields) is still available.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 5.2.6 (upgraded from 4.10.5)
- Calendar Version: 5.0.6
- Calendar Edition: Lite
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Hi @btbunze,

Have you run the following in your command line interface? 🙂 

`./craft calendar/events/fix-titles`

https://docs.solspace.com/craft/calendar/v5/developer/console-commands/#migrate-craft-4-element-titles

**Comment by btbunze** [comment]
Hi @kjmartens,

I hadn't! Running it seems to have solved my problem. Thank you.

**Comment by darylknight** [comment]
Stumbled across this when all of my content disappeared too. This is why plugins have different major versions for different versions of Craft.
