### ISSUE TITLE
Unable to import feed with some RRULES

### ISSUE THREAD

**Issue by chrisrowe** [solspace/craft3-calendar#304]
**Describe the bug or issue you're experiencing**

`Cannot assign null to property Solspace\Calendar\Bundles\ExternalPluginSupport\FeedMe\CalendarIntegration::$rruleInfo of type array`

Looks like in https://github.com/solspace/craft-calendar/blob/c5fe3d8fa274cfca3a1d60aeed2024b933442b1b/packages/plugin/src/Bundles/ExternalPluginSupport/FeedMe/CalendarIntegration.php#L40 this should be `private array|null $rruleInfo = [];`

**Steps to reproduce**

1. Define a feed where some events have RRULES and some dont
2. Use feed-me to import them

**Expected behavior**

All events imported

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.10.6
- Calendar Version: 5.0.6
- Calendar Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Sorry for the delay, and thank you for this @chrisrowe. We'll check into it very soon. 🙂

**Comment by kjmartens** [comment]
This should be resolved in Calendar 5.0.7 now. 🙂
