### ISSUE TITLE
Craft 5 - Multiple instanced fields on events will not save values

### ISSUE THREAD

**Issue by gregorterrill** [solspace/craft3-calendar#315]
It appears that in Craft 5, if you add multiple instances of a field to the field layout of a calendar (with different labels / handles, but the same underlying field), only the first instance of that field will actually save its value. The rest of them are all blank.

Steps to reproduce:

1. Create a calendar.
2. Add the same field multiple times to that calendar's field layout, changing the label and handle for each one.
3. Create an event in that calendar.
4. Fill out all fields and save.
5. Only the first custom field will have its value saved, the others will be blank.

Version info:

- Craft Version: 5.3.4
- Calendar Version: 5.0.7
- Calendar Edition: Pro (trial)

**Comment by strandofgenius** [comment]
I am also having this issue with Calendar 5.0.7

**Comment by gregorterrill** [comment]
I actually just noticed a likely related issue as well - in the calendar config screen, the "ICS Description field" and "ICS Location field" dropdowns only show the original non-instanced field names. So for example, I have a "Short Text" base field with two instances "Excerpt" and "Pricing Info" in the layout. I would expect to see "Excerpt" and "Pricing Info" as options in the dropdown, but instead I only see one "Short Text" option. Seems like the plugin just doesn't recognize instanced fields.

**Comment by kjmartens** [comment]
Sorry about this. We'll investigate this issue shortly. 🙂

**Comment by seandelaney** [comment]
PR includes fix for the "ICS Description field" and "ICS Location field" dropdowns too.

**Comment by kjmartens** [comment]
These issues are now resolved in Calendar 5.0.9+ 🙂
