### ISSUE TITLE
Fresh Craft CMS install with Calendar plugin in Project Config broken

### ISSUE THREAD

**Issue by qrazi** [solspace/craft3-calendar#316]
**Describe the bug or issue you're experiencing**

When doing a fresh install of a Craft CMS project with the Calendar plugin already defined in Project config, the install fails due to mismatching schemaVersions. Would be happy to try and create a PR. Looking into the cause - a change in Craft CMS - made me wonder why Calendar plugin is not using `\craft\base\Plugin::$schemaVersion` property? If it would, it would also resolve this issue.

See below for the details as to why it fails.

**Steps to reproduce**

1. Project config defines Calendar plugin as installed
2. Install Craft CMS - e.g. `./craft install/craft`
3. Install fails with message
```
*** installing Craft

Project config validation failed: Calendar is installed with schema version 1.0.0, but project.yaml expects 5.0.0.

Run `composer install` or remove your `config/project/` folder and try again.

Aborting install.
```

**Expected behavior**

1. Project config defines Calendar plugin as installed
2. Install Craft CMS - e.g. `./craft install/craft`
3. Install runs successfully and ends with message something like "Install success"

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.11.3
- Calendar Version: 5.0.7
- Calendar Edition: Pro
- Fresh Install or Upgrade: Fresh

**Additional context**
- Related to previous issue #297 
- Again caused by changed in the validation done by Craft CMS during install
- Affects Craft CMS 4 (since 4.11.2) and Craft CMS 5 (since 5.3.2)
  - https://github.com/craftcms/cms/compare/4.11.1...4.11.2#diff-ef4bf19c7da8efc04d1c70f9e6ed69d15053964c85d4770e8be724e8e13da704
  - https://github.com/craftcms/cms/compare/5.3.2...5.3.3#diff-ef4bf19c7da8efc04d1c70f9e6ed69d15053964c85d4770e8be724e8e13da704

**Comment by qrazi** [comment]
Note: I just modified `vendor/solspace/craft-calendar/packages/plugin/src/Calendar.php` locally to include `\craft\base\Plugin::$schemaVersion` and ran into the next plugin where the same happened. So I'm also going to open an issue on Craft CMS repo.

**Comment by qrazi** [comment]
So, opened an issue on Craft CMS repo: https://github.com/craftcms/cms/issues/15559

**Comment by kjmartens** [comment]
Thanks for reporting this @qrazi.

We'll update things from our end as well, assuming it's a necessary change. 🙂
