### ISSUE TITLE
Calendar fields not translated

### ISSUE THREAD

**Issue by joostclevis** [solspace/craft3-calendar#318]
**Describe the bug or issue you're experiencing**

The fields added to the calendar are not translated. It gets overridden every time you change the contents of a field, event though the fields are set to be translatable by site. Adding a new field has the same issue. Changing the way a field is translatable doesn't solver the issue.

**Steps to reproduce**

1. Add translatable field to calendar
2. Add content to field
3. Change text in other language
4. Go back to other language to see text is overridden

**Expected behavior**
Translate the fields and don't override them.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 5.3.5 
- Calendar Version: 5.0.7
- Calendar Edition: Lite
- Fresh Install or Upgrade: Upgrade

**Comment by ThomasDeMarez** [comment]
We are experiencing the same issue.
It does not matter if it's a Craft native field or one from a Plugin (Linkit, ...) the value for the field gets overwritten in all other sites.

**Comment by joostclevis** [comment]
@kjmartens any updates on this issue?

**Comment by kjmartens** [comment]
Sorry about this @joostclevis and @ThomasDeMarez.

I can duplicate this in my testing as well. Seems to happen only on Craft 5. We'll work on a fix for it hopefully this week. 🙂
