### ISSUE TITLE
Dismissing the "Get calendar up and running" message on Project Config sites causes an error

### ISSUE THREAD

**Issue by darylknight** [solspace/craft3-calendar#33]
**Describe the bug or issue you're experiencing**

On environments where administrative changes are disallowed, like staging and production on Project Config sites, the banner for installing the demo templates still appears. When you dismiss it, a server error occurs because this is stored in project config, but you can't edit that on staging/production.

Banner:
![image](https://user-images.githubusercontent.com/1250017/111754181-5ceb4700-88a0-11eb-994d-5c1f431bc994.png)

Clicking the X causes this error:
```
2021-03-19 01:45:37 [-][1][-][error][yii\web\HttpException:403] yii\web\ForbiddenHttpException: Administrative changes are disallowed in this environment. in /srv/users/app-name/apps/app-name/vendor/craftcms/cms/src/web/Controller.php:318
```

**Expected behavior**
Probably remove that banner entirely on environments where admin changes aren't allowed.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.6.10
- Calendar Version: 3.2.1
- Calendar Edition: Pro

**Comment by kjmartens** [comment]
Thanks @darylknight. This is a good idea... we can likely hide this banner altogether when the `allowAdminChanges` setting is disabled. :)

**Comment by gustavs-gutmanis** [comment]
Thanks for reporting this @darylknight, it will be fixed in the upcoming release.
