### ISSUE TITLE
Circular migration/project config write operations from #324

### ISSUE THREAD

**Issue by aaronbushnell** [solspace/craft3-calendar#333]
I'm upgrading to the latest version of Calendar on a Craft 4.x project, but the migration introduced in #324 is causing issues.

Here's what happens:

1. Setup Craft using Calendar 5.0.8 and commit all changes in Git
2. Create a SQL backup
3. Upgrade to Calendar 5.0.9 and run the migration that comes with it
4. At this point you'll have changes to your project config you need to commit. Commit them

This is where we typically simulate a production deploy when we perform Craft/plugin updates. So we:
1. Import the current production database (this is why we create a SQL backup in step 2)
2. Run `php craft up` and run the migrations
3. Review the site to verify all is well

The problem is re-running the migration _mutates_ the UUIDs in the project config again. So now your upgrade process spawns changes that haven't been committed to the codebase). This means running this upgrade in production is going to write project config changes instead of just replaying the ones we made locally.

Hopefully this made sense!

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.12.6
- Calendar Version: 5.0.9
- Calendar Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by seandelaney** [comment]
Sorry about this @aaronbushnell. I have reopened a new PR, changing how we fix duplicates 🙂

**Comment by aaronbushnell** [comment]
Thanks, @seandelaney!

**Comment by kjmartens** [comment]
This is now updated in Calendar 5.0.10. 🙂

**Comment by aaronbushnell** [comment]
Thank you!
