### ISSUE TITLE
The `getOccurrences` method on `Event` should consider `rangeStart` when assuming `rangeEnd` for an infinite `Event`.

### ISSUE THREAD

**Issue by msimpson** [solspace/craft3-calendar#349]
The `getOccurrences` method on `Event` should consider `rangeStart` when assuming `rangeEnd` for an infinite `Event`.

https://github.com/solspace/craft-calendar/blob/6559b22faf2f4fba7a5f562910466f185a2b213a/packages/plugin/src/Elements/Event.php#L1138-L1146

If `getOccurrences` is called on an infinite `Event` where:

&nbsp;&nbsp;&nbsp;&nbsp;(1) `rangeStart` is a datetime more than six month into the future; and

&nbsp;&nbsp;&nbsp;&nbsp;(2) `rangeEnd` is `null`;

then, the `rangeEnd` will be assumed to be `new \DateTime('+6 months')`.

Positioning `rangeEnd` prior to `rangeStart`, resulting in a nonsensical range.

**Comment by kjmartens** [comment]
Sorry for the delay @msimpson.

Thank you for this. We will review and implement the change shortly, assuming it's a valid one. 🙂

**Comment by kjmartens** [comment]
This should be resolved in Calendar 5.0.13+ now. 🙂 

Thanks for your patience.
