### ISSUE TITLE
Calendar doesn't support Project Config for fields

### ISSUE THREAD

**Issue by darylknight** [solspace/craft3-calendar#35]
**Describe the bug or issue you're experiencing**
I just launched a new feature on a client site, where I added a new field to calendar events. I deployed and expected no other changes needed, until I realised that the field hadn't been added to the event on the live server. Looks like Calendar events aren't using Project Config. Is this on the roadmap?

**Steps to reproduce**

1. Add a field locally to a calendar
2. Deploy
3. Have to add the field again on the new environment

**Expected behavior**
Project Config should be recording field changes and update the other environment on running `./craft project-config/apply`

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.6.11.2
- Calendar Version: 3.2.1
- Calendar Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Hi @darylknight,

Sorry for the delay in responding to this request. We've added support for Project Config on field layouts and other calendar data in calendars now. If you'd like to try it out, it's available in v3.3.0. :)

**Comment by darylknight** [comment]
Thanks Kelsey! Will try it out the next time we do maintenance on that website.
