### ISSUE TITLE
When ICS Export description/location are not filled in an error occurred

### ISSUE THREAD

**Issue by MvdO79** [solspace/craft3-calendar#350]
**Describe the bug or issue you're experiencing**

In a calendar settings page when not filling in the ICS Export description/location an error occures when clicking the export event button.

**Steps to reproduce**

1. Leave the ICS Export description/location fields empty and click on an event's export event button.

**Expected behavior**

Prevent the error by changing the if statements so that the ICS Export description/location fields values are excluded when empty and the event is exported to ICS without these values.

**Craft & Plugin Info (please complete the following information):**

- Craft Version:
Pro 5.4.9
- Calendar Version:
5.0.12
- Calendar Edition:
Pro
- Fresh Install or Upgrade:
Fresh

**Comment by kjmartens** [comment]
Sorry about this @MvdO79,

We'll get it the issue resolved shortly. 🙂

**Comment by MvdO79** [comment]
> Sorry about this @MvdO79,
> 
> We'll get it the issue resolved shortly. 🙂

Thank you @kjmartens

**Comment by kjmartens** [comment]
This should be resolved in Calendar 5.0.13+ now. 🙂 

Thanks for your patience.
