### ISSUE TITLE
When ICS Export description/location values are filled in they are not shown in the generated event ICS file

### ISSUE THREAD

**Issue by MvdO79** [solspace/craft3-calendar#351]
**Describe the bug or issue you're experiencing**

When the ICS Export description/location are filled in in a calendar settings page the values are not shown in the generated event ICS file.

**Steps to reproduce**

1. Fill in the ICS Export description/location fields and click on an event's export event button.
2. Open the generated ICS file and view the missing description and location values.

**Expected behavior**

Prevent the missing values by changing the if statements so that the ICS Export description/location fields values are included when filled in.

**Craft & Plugin Info (please complete the following information):**

- Craft Version:
Pro 5.4.9
- Calendar Version:
5.0.12
- Calendar Edition:
Pro
- Fresh Install or Upgrade:
Fresh

**Comment by kjmartens** [comment]
Sorry for the delay @MvdO79,

When I test this on my end, it seems to work okay. Can I ask what kind of field types you have mapped to the ICS Location and ICS Description field settings? 🙂

**Comment by MvdO79** [comment]
Hi @kjmartens, thanks for your reply. I used a ckeditor type field for the description field. And I used a plain text type field for the location field.

**Comment by kjmartens** [comment]
Hi @MvdO79,

Advanced field types are not supported for the ICS fields at this time, unfortunately. It's on our list for future consideration, however. 🙂 

I am wondering if/assuming that maybe the CKEditor type is breaking the Location field mapping as well... can you see if mapping a different text field type (or none at all, if using next 5.0.13 version of Calendar that fixes the other #350 issue) gets the Location field working?
