### ISSUE TITLE
Garbage collector from CLI fails with error " Base table or view not found"

### ISSUE THREAD

**Issue by qrazi** [solspace/craft3-calendar#352]
**Describe the bug or issue you're experiencing**

When running Craft CMS garbage collection from the command line the following error occurs and garbage collecting doesn't finish running: 
`Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'feadship-craft3_local.calendar_calendars' doesn't exist`

**Steps to reproduce**

1. Craft CMS 4 project
2. Set a `tablePrefix`
3. Run on CLI: `./craft gc`
4. Keep default "no" option

**Expected behavior**
Craft CMS successfully deletes all different types of content from its tables during the garbage collection run.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.13.3
- Calendar Version: 5.0.12
- Calendar Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
Also creating a PR to go with this issue.

**Comment by seandelaney** [comment]
PR merged and fix will be available in the next release.

**Comment by seandelaney** [comment]
PR merged and fix will be available in the next release.
