### ISSUE TITLE
Poor performance on month view with lots of events

### ISSUE THREAD

**Issue by gijsstegehuis** [solspace/craft3-calendar#39]
**Describe the bug or issue you're experiencing**
When loading the month view with lots of events (e.g. 290 records) it becomes very sluggish.
It takes about 4 seconds for the XHR to load.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.6.13
- Calendar Version: 3.2.1
- Calendar Edition: Pro
- Fresh Install or Upgrade: x

**Comment by gijsstegehuis** [comment]
anyone?

**Comment by gustavs-gutmanis** [comment]
Hi @gijsstegehuis 
There is definitely a bottleneck with events that have lots of recurrences, could you describe the types of events you have?  
Are you using any custom fields attached to them, what are the most common recurrence rules?

**Comment by gijsstegehuis** [comment]
Hi @gustavs-gutmanis. None of them seem to be recurring.
We're using about 20 calendars that use the same fieldlayout, but are unique to a certain person.
The only relevant custom field is a custom field type that resolves an element in it's `normalizeValue()`

**Comment by gustavs-gutmanis** [comment]
Is it possible for you to enable the [Yii's debug toolbar](https://nystudio107.com/blog/profiling-your-website-with-craft-cms-3s-debug-toolbar) and check how many database requests are generated? I have a feeling that resolving elements generates a new query per resolved element.

**Comment by gijsstegehuis** [comment]
Hi @gustavs-gutmanis. I tried that already, but profiling doesn't work for the XHR's.

I managed to cut the loading time in half by caching some stuff in normalizeValue, but the month XHR still takes 2 seconds to load.
That's still quite slow. Maybe you can limit the amount of events per day for the initial view?

**Comment by gustavs-gutmanis** [comment]
Unfortunately, there's not much we can do without refactoring the way events are built and stored.

How many events per day do you have? Due to having the events be built virtually instead of storing each recurrence in the database - the calendar has to look in the past and the future to see if it's not missing any events based on the rules, so reducing the lookup might cause events not being shown.
