### ISSUE TITLE
Efficient event queries

### ISSUE THREAD

**Issue by sebastian-lenz** [solspace/craft3-calendar#4]
Congratulations for releasing the beta!

I've looked into the EventQuery class and currently don't know how to efficiently query for events within a certain range. Maybe I'm missing something?

The methods `EventQuery::setStartDate`, `EventQuery::setEndDate` and `EventQuery::setUntil` don't allow to pass an operator as the passed argument is instantly converted to a DateTime/Carbon instance, hence any prepended operators produce an error. In `EventQuery::beforePrepare` the values are passed to `Db::parseParam` which would inject operators, but I don't see no way to pass them here. 

The opposite of `EventQuery::setUntil` is missing, shouldn't there be something like `EventQuery::setFrom`?

Currently we can use `EventQuery::setRangeStart` and `EventQuery::setRangeEnd` to query a certain date range, but there seems to be no preselecting of events in `EventQuery::beforePrepare` going on. So as far as I understand the code, the entire calendar will be loaded when using `rangeStart` or `rangeEnd` and the events will be filtered by code?

**Comment by sebastian-lenz** [comment]
`EventQuery::setRangeStart` and `EventQuery::setRangeEnd` don't work for single events as they are not handled in `EventQuery::cacheSingleEvents`?

**Comment by gustavs-gutmanis** [comment]
This was a bug, and is now taken in consideration when building the queries and executing them. Use `rangeStart` and `rangeEnd` to specify date ranges.
This will be available in the upcoming `v2.0.0-beta.3` version. Thanks for letting us know!
