### ISSUE TITLE
GraphQL query returns an error if the query contains a fragment

### ISSUE THREAD

**Issue by jonathanmelville** [solspace/craft3-calendar#46]
If you attempt to make a GraphQL query to Calendar and that query contains a fragment, the query will result in an error. Interestingly this is only reproducible when `devMode` is false. If `devMode` is true, the query will succeed.

**Steps to reproduce**

1. Make a query similar to this when devMode is disabled:
```
fragment myCalendarFields on events_Event {
  eventCategory {
    slug
    title
  }
  eventDescription
}

query getMonthEvents {
  solspace_calendar {
    events {
      id
      title
      startDateLocalized
      endDateLocalized
      allDay
      freq
      ...myCalendarFields
    }
  }
}
```

**Expected behavior**
The query should succeed. 

**What actually happens**
```
2021-06-23 17:45:34 [-][-][-][error][craft\errors\GqlException] craft\errors\GqlException: Tried to load an unregistered type "events_Event". This can indicate both a typo in the query or an issue with the schema used. in .../.../vendor/craftcms/cms/src/gql/TypeLoader.php:39
```

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.6.17
- Calendar Version: 3.3.1
- Calendar Edition: Pro 
- Fresh Install or Upgrade: Fresh

**Additional context**

In `devMode` this isn't a problem. It's only reproducible when `devMode` is disabled.

**Comment by gustavs-gutmanis** [comment]
Hi @jonathanmelville,  
I have set up my query to look like yours and it works both in `devMode` and without it.  
The error you're getting says the type is not loaded, which could happen if you were using a different environment, but the `devMode` flag should not be causing this. Does this only happen on production or on your local dev environment as well?

**Comment by jonathanmelville** [comment]
Hi,

I only get this error in production. I pulled the production DB down to my local environment and executed the same query and it worked. So next I tried enabling devMode on the production server, and with devMode enabled the query succeeded. When I disabled devMode again the query failed.

**Comment by gustavs-gutmanis** [comment]
Unfortunately, this sounds like an edge-case scenario with your production environment.  
If I cannot reproduce it, I can't really fix it...

**Comment by jonathanmelville** [comment]
@gustavs-gutmanis Understand, I will just keep my workaround in place for now, it's not the end of the world. Thank you for looking into it for me.

**Comment by mildlygeeky** [comment]
@gustavs-gutmanis I ended up working with @jonathanmelville on this - really oddly, putting the fragment _after_ the query made it work, while putting the fragment before the query would issue the TypeLoader error (without devMode on).

Given that the Gql code for Craft pre-loads schema (and notes in the comments that lazy loading will kick in without devMode on), it feels like maybe the Solstice events are properly getting that lazy loading treatment, and so only work in fragments when the loader has already seen the other Calendar stuff?

![screen_shot_2021-06-24_at_12 33 24_pm](https://user-images.githubusercontent.com/273266/123361161-8de0b500-d53c-11eb-88b2-988ebddd3bcf.png)

**Comment by gustavs-gutmanis** [comment]
I will ask Pixel & Tonic about this, maybe there's something that can be done.  
Thanks @mildlygeeky!
