### ISSUE TITLE
SQLSTATE[42P01]: Undefined table: 7 ERROR: missing FROM-clause entry for table "calendarsites"

### ISSUE THREAD

**Issue by RyVeata** [solspace/craft3-calendar#48]
**Describe the bug or issue you're experiencing**

On upgrading Calendar from 3.2.1 to 3.3.0 on Craft 3.6.17 Postgres database throws the error:

```
SQLSTATE[42P01]: Undefined table: 7 ERROR: missing FROM-clause entry for table "calendarsites"
The SQL being executed was: SELECT calendarSites."id", calendarSites."uid", calendarSites."calendarId", calendarSites."siteId", calendarSites."enabledByDefault", calendarSites."hasUrls", calendarSites."uriFormat", calendarSites."template"
FROM "calendar_calendar_sites" "calendarSites" WHERE "calendarId"=1
ORDER BY "id"
```

The issue is caused by the camelCase definition of 'calendarSites' used in the getQuery() function of packages/plugin/src/Services/CalendarSitesService.php which Postgres is changing to lowercase and which then does not get recognised within the query. This is using Postgres 10.4, I am unsure if the failure to accept the camelCase is ultimately due to using an older Postgres version.

**Steps to reproduce**

1. Build a craft install with multi site set up
2. Install Calendar 3.2.1
2. Add test calendar and event
3. update to Calendar 3.3.0 or later
4. Visit calendar settings in admin panel
5. See error 

**Expected behavior**

No errors would show.  The calendar section of the admin panel, and calendar event pages within the multi site will display.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.6.17
- Calendar Version: 3.3.0
- Calendar Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**

I have tested changing the references in the getQuery() function to 'calendarsites' and this has resolved the issue for me. Attached is a PDF of the error in full.
[calendar-error.pdf](https://github.com/solspace/craft3-calendar/files/6756193/calendar-error.pdf)

**Comment by kjmartens** [comment]
Sorry for the trouble. It seems this is the same issue as reported here:
https://github.com/solspace/craft3-calendar/issues/40

I'll close this one and we'll discuss it further on the other issue report. :)
