### ISSUE TITLE
Lots of duplicate events created 

### ISSUE THREAD

**Issue by justinholtweb** [solspace/craft3-calendar#49]
**Describe the bug or issue you're experiencing**
Client has around 4.5k events running back to 1989, they use the old events as a source of data for a timeline feature. Recently they noticed performance lags on searching for events and happened to notice that their events total jumped from 4.5k to over 26k. I investigated and found older events had duplicates created, sometimes up to 6 duplicates per event. This seems to happen on events 12/2018 and older. This doesn't happen on new events created. 

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.6.14
- Calendar Version: 3.3.1
- Calendar Edition: Lite
- Fresh Install or Upgrade: Upgrade

**Additional context**

I'm happy to provide a login to the production instance and/or DB export.

**Comment by gustavs-gutmanis** [comment]
@justinholtweb, this has never been reported before, so my first guess is that this is something that has happened in a data migration or something which you have been running.

If you can reproduce this and you can find out that Calendar is the culprit, we'll gladly help, but currently there's not enough for us to go on, sorry.
