### ISSUE TITLE
EventsService calling site instead of siteId

### ISSUE THREAD

**Issue by samstevens** [solspace/craft3-calendar#5]
Hi guys,

When calling craft.calendar.event() variable, if you include site or siteId in the options, this correctly works out the siteId however once this gets called in EventsService.php, it's calling "site" instead of "siteId" in the query.

`solspace/craft3-calendar/src/Services/EventsService.php:56`

This appears to fix the problem.

```    public function getEventBySlug(string $slug, string $site = null): Event
    {
        return Event::find()
            ->slug($slug)
            ->setAllowedCalendarsOnly(false)
            ->enabledForSite(false)
            // HOTFIX
            //->site($site)
            ->siteId($site)
            ->one();
    }
```

Thanks :)

**Comment by gustavs-gutmanis** [comment]
Thanks for finding this! Fixed in the upcoming version.
