### ISSUE TITLE
Doesn't work with supertable

### ISSUE THREAD

**Issue by stephanedemotte** [solspace/craft3-calendar#58]
Got an error when i try to add a [supertable](https://plugins.craftcms.com/super-table) field into an event
```
Calling unknown method: verbb\supertable\elements\db\SuperTableBlockQuery::hasTitleField()
```

**Comment by kjmartens** [comment]
@stephanedemotte I just installed and set up Super Table now. I was unable to duplicate any issues between the 2 plugins. Perhaps I am doing something a bit different from what you're doing. Would you be able to provide us with more information about your setup, how the Super Table field is configured, how the Calendar calendar is setup, etc? :)

**Comment by stephanedemotte** [comment]
Wierd it's working now.... so sorry for the noise ! :)
