### ISSUE TITLE
Resaving of entries

### ISSUE THREAD

**Issue by samstevens** [solspace/craft3-calendar#6]
If I create a new calendar, and then make a change to this calendar's settings, this causes a re-save of any existing entries.

There appears to be an issue with the task which does this.

I'm getting the following error

```
description:"Resaving Public Calendar events (Site 1)"
error:"Getting unknown property: Solspace\Calendar\Elements\Event::"
```

Thanks :)

**Comment by gustavs-gutmanis** [comment]
This has been fixed in the upcoming version
