### ISSUE TITLE
Element editor slideout doesn't display title or date fields  

### ISSUE THREAD

**Issue by mikejpeters** [solspace/craft3-calendar#67]
**Describe the bug or issue you're experiencing**

In the control panel, when viewing an entry with a _Calendar Events_ field, double clicking on the related event opens the [Element Editor Slideout](https://craftcms.com/knowledge-base/upgrading-to-craft-3-7#element-editor-slideouts) but only custom fields are displayed.

![Screenshot from 2021-09-01 08-46-03](https://user-images.githubusercontent.com/3334654/131703515-8709fe50-be79-4333-a16e-9921ad15bd65.png)

**Steps to reproduce**

1. Create a custom _Calendar Events_ field and and add it to an entry type
2. Create/edit an entry and select an event
3. Double-click on the selected event

**Expected behavior**

It would be great if all event fields were editable from the slideout.

**Craft & Plugin Info:**

- Craft Version: 3.7.8
- Calendar Version: 3.3.3
- Calendar Edition: Pro
- Fresh Install or Upgrade: Fresh Install

**Comment by kjmartens** [comment]
@mikejpeters Sorry for the trouble and the delay. We'll check into this and see what we can do to resolve it shortly. :)

**Comment by kjmartens** [comment]
This is fixed now in Calendar 3.3.5.

**Comment by kjmartens** [comment]
@mikejpeters Maybe it's cache? I can't duplicate that behavior on my end...

**Comment by mikejpeters** [comment]
I looked into it more - the slideout works fine on regular entries, but not on products (with Commerce).

I tested by creating a new project with the latest versions of Craft, Calendar, and Commerce:
-  Craft CMS 3.7.13
-  Calendar PRO 3.3.5
-  Craft Commerce LITE 3.4.2

I created an Event field and added it to the default product type (Clothing) that Commerce sets up.
When I edit any products I get the same issue I described above: all fields show the first time the slideout opens, but only custom fields show on subsequent opens.

Maybe it's because Commerce is a bit more JS-heavy and something is conflicting?

However there are no console errors, and `observer:>>` is logged to the console.

I can deploy the demo site so you can see the issue, but I'm hoping that you can reproduce the issue easy enough with the info I provided here. Thank you!

**Comment by kjmartens** [comment]
@mikejpeters Ok, I can duplicate this on my end as well. I'm not sure why it's happening just in Commerce products, but we'll have a look into it. 🙂
