### ISSUE TITLE
Issue setting the calendar event template urls and template paths

### ISSUE THREAD

**Issue by samstevens** [solspace/craft3-calendar#7]
When creating or editing a calendar's settings, the section for:

**Site Settings**
_Choose which sites this calendar should be available in, and configure the site-specific settings._

This doesn't appear to set up the routing correctly. The urls for the events are set correctly however the routing to the template doesn't appear to work. It throws a regular 404.

`HTTP 404 – Not Found – yii\web\NotFoundHttpException
`

Thanks :)

**Comment by kjmartens** [comment]
Sorry for the delay... we'll have a fix for this in the next version of Calendar (beta 7) :)
