### ISSUE TITLE
Pagination breaks event sorting

### ISSUE THREAD

**Issue by joshwalsh** [solspace/craft3-calendar#77]
The `/admin/calendar/events` presents a table of calendar events which can be sorted alphabetically by title by clicking on the table header.

Pagination breaks this sort.  Specifically, when you navigate to the 2nd page the results are no longer in alphabetical order (I believe they are in database order).

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.13
- Calendar Version: 3.3.4
- Calendar Edition: Pro

**Comment by kjmartens** [comment]
Sorry for the trouble @joshwalsh. This is unfortunately part of a bigger issue that isn't easily fixed. With Calendar handling recurrences and running into potential performance issues, we made some architectural decisions to help achieve this, but there have been some negative effects such as the behavior you describe. We do hope to address these kinds of issue with large rewrites of the plugin in the future.
