### ISSUE TITLE
Calendar events in the control panel taking 30 seconds to load

### ISSUE THREAD

**Issue by jonathanmelville** [solspace/craft3-calendar#79]
**Describe the bug or issue you're experiencing**
When visiting the `/admin/calendar` route in the control panel, the XHR that fetches the events for the month view is taking 30 seconds or more to complete.

**Steps to reproduce**

1. Go to the Calendar page in the control panel.

**Expected behavior**
The Calendar page should load faster.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft CMS 3.7.17.2
- Calendar Version: Calendar 3.3.5
- Calendar Edition: Pro
- Fresh Install or Upgrade:

**Additional context**
Also, navigation between months takes a similarly long time to complete. There is only one calendar, events do make use of custom fields. They also have some recurring events.

Is there anything that can be down to bring this load time down or debug this?

**Comment by jonathanmelville** [comment]
@kjmartens Can also provide CMS/Server access if needed.

**Comment by kjmartens** [comment]
@jonathanmelville We set up a new install with similar environment as yours (PHP8, MySQL 8, etc) and saw no issues. We then loaded your database dump and continued to see no issues. One thing to note though... after reviewing your database, it appears that you may have manually added a primary key column to the `calendar_events` database table (likely in an effort to help with MySQL 8 support)? Can you confirm if you've made this change or other manual changes to your database?

**Comment by jonathanmelville** [comment]
@kjmartens This is required by DigitalOcean managed databases, all tables must have a primary key. This would be the only change to be made manually.

Can you login to our control panel and see for yourself the load time on this?

**Comment by kjmartens** [comment]
@jonathanmelville Sure, can you send the login via email? :)

**Comment by jonathanmelville** [comment]
@kjmartens To Support address?

**Comment by kjmartens** [comment]
@jonathanmelville Yes

**Comment by jonathanmelville** [comment]
@kjmartens Sent.

**Comment by jonathanmelville** [comment]
@kjmartens Thanks for helping me look into this. I'm going to close this since the issue has moved to the Craft team.

**Comment by kjmartens** [comment]
@jonathanmelville Would you be able to try updating to `dev-master` version and see if the latest fix corrects this now? :)

**Comment by jonathanmelville** [comment]
Hey @kjmartens, it fails on the migration. It looks like it's trying to add a primary key to the `calendar_events` table when one already exists.

<img width="2607" alt="Image 2021-11-08 at 1 20 22 PM" src="https://user-images.githubusercontent.com/7415693/140796672-f6e79ec2-0a12-483e-9bd4-bd80cfead698.png">

**Comment by gustavs-gutmanis** [comment]
Hi @jonathanmelville,

It fails because of your manual tempering with the `calendar_events` table. You set the primary key manually for it to be compatible with the digital ocean server, right?  
Could you just bypass the migration in the files directly, by returning `true` at the beginning of the `safeUp()` function in [packages/plugin/src/migrations/m211001_063936_AddPrimaryKeyForEventsTable.php](https://github.dev/solspace/craft3-calendar/blob/f40cc2412a1251b91f17b9b3bd28aa0fc317e524/packages/plugin/src/migrations/m211001_063936_AddPrimaryKeyForEventsTable.php#L1)?

**Comment by jonathanmelville** [comment]
@kjmartens Bypassing the migration worked. And yes I had to add a primary key to this table myself, it's required by Digital Ocean when using the managed DB service.

Unfortunately this did not resolve the issue. After updating to `dev-master`, I reloaded the calendar page and it took 1m45s for calendar events to load.

**Comment by gustavs-gutmanis** [comment]
@jonathanmelville try the latest `dev-master` version, please.

**Comment by jonathanmelville** [comment]
Hey @gustavs-gutmanis, I'm getting this when running the update:

```
> @php craft project-config/apply
Your project config files were created for different versions of Craft and/or plugins than what’s currently installed.

Calendar is installed with schema version of 3.3.2 while 3.3.0 was expected.

Try running `composer install` from your terminal to resolve.
Script @php craft project-config/apply handling the craft-update event returned with error code 1
Script @craft-update was called via post-update-cmd
```

Running `composer install` does not resolve it.

**Comment by gustavs-gutmanis** [comment]
Very strange. The schema version updated a month ago along with the `v3.3.5` update. I wonder why you didn't run into this issue just a little while ago with the previous update, since the `composer.json` hasn't been changed 🤔 
How did you install the previous update to `dev-master`?

**Comment by jonathanmelville** [comment]
Hey @gustavs-gutmanis, I think this was because my development database was in a strange state from trying to run the previous update. I pulled down a fresh one, bypassed the migration as last time and everything installed.

This update worked!!!! So two questions, I guess I need to wait and deploy when when you merge it into a release? And also, because my database already has a primary key on the calendar_events table, how should I handle rolling out this update to production?

THANK YOU for looking into this for me and finding a solution.

**Comment by gustavs-gutmanis** [comment]
Since yours is a special case, I would suggest you either alter the migration file just like you did for this environment, or insert the migration in the production's `migrations` table, so that it skips it.

You're welcome, glad we got this resolved!

**Comment by jonathanmelville** [comment]
@gustavs-gutmanis I will manually insert the migration into the migrations table, thanks again!

**Comment by jonathanmelville** [comment]
@gustavs-gutmanis Do you know when this will be merged into a release?

**Comment by kjmartens** [comment]
We'll release it today. :)
