### ISSUE TITLE
Date translation

### ISSUE THREAD

**Issue by alexanderbuergin** [solspace/craft3-calendar#82]
The dates can't be translated with the `| t` filter. I'm trying to translate something like this `card.endDate.format('l, j. F Y')` from en to de.

**Comment by kjmartens** [comment]
You'll want to use the `|date` filter instead. However, that will run into localization issues, so be sure to use the `Localized` version of each date variable:

`card.endDateLocalized|date('l, j. F Y')`

**Comment by alexanderbuergin** [comment]
Works, thanks :)
