### ISSUE TITLE
Month.(start)Date incorrect when using groupedByMonth()

### ISSUE THREAD

**Issue by ThinkGraphical** [solspace/craft3-calendar#85]
**Describe the bug or issue you're experiencing**
I'm noticing that month.(start)Date is incorrect when using groupedByMonth()

**Steps to reproduce**

1. Create an multi-day event spanning 2 months (for example: from dec 27th until jan 9th)
2. Use following simplified template
```
{% set eventsGroupedByMonth = craft.calendar.events({
    ...
    rangeStart: 'today',
}).groupedByMonth() %}

{% for month in eventsGroupedByMonth %}
    <h2>{{ month.startDate|date('F') }}</h2>

    {% for event in month.events %}
        <h3>
            {{ event.startDate|date('d/m') }} - {{ event.endDateDate|date('d/m') }}
        </h3>
    {% endfor %}
{% endfor %}
```

**Expected behavior**

You would expect following output: 
```
    <h2>december</h2>
        <h3>27/12 - 10/01</h3>
    <h2>january</h2>
        <h3>27/12 - 10/01</h3>
```

But get:
```
    <h2>december</h2>
        <h3>27/12 - 10/01</h3>
    <h2>december</h2>
        <h3>27/12 - 10/01</h3>
```

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.20
- Calendar Version: 3.3.7
- Calendar Edition: Lite
- Fresh Install or Upgrade: Fresh install

**Additional context**

I suspect it got something to do with line 584 in `Elements/Db/EventQuery.php`.
`$grouped[] = new MonthDuration($firstEvent->getStartDate(), $events);`

Where the $firstEvent->getStartDate() is dec 27th

**Comment by kjmartens** [comment]
Sorry for the trouble @ThinkGraphical. I can duplicate this in my testing as well. We'll make a fix for it soon. 🙂

**Comment by gustavs-gutmanis** [comment]
Thanks for reporting this @ThinkGraphical, this issue has been addressed now and will be released with the next version.
