### ISSUE TITLE
Select dates are not saved when editing via slideout

### ISSUE THREAD

**Issue by mikejpeters** [solspace/craft3-calendar#86]
**Describe the bug or issue you're experiencing**

Editing an event using the slideout does not update the repeating dates for an event that repeats every "Select dates".

**Steps to reproduce**

1. Create a custom Calendar Events field and and add it to an entry type
2. Create/edit an entry and select an event
3. Double-click on the selected event
4. Make changes to the "Repeats" options so that it repeats every "Select dates" and specify some dates
5. Press Save

![image](https://user-images.githubusercontent.com/3334654/143952884-330537dd-5a69-498b-9896-b26184cebe09.png)

**Expected behavior**

Event should be updated with the selected dates.

**Craft & Plugin Info:**

- Craft Version: 3.7.23
- Calendar Version: 3.3.7
- Calendar Edition: PRO
- Fresh Install or Upgrade: Upgrade

**Additional context**

I think maybe this happens because the slideout submits to Craft's `elements/save-element` action,
but the select dates are only saved in `EventsController::actionSaveElement()`: 

https://github.com/solspace/craft3-calendar/blob/d929c51c273495d12e007d3cb9e940ea8ade5393/packages/plugin/src/Controllers/EventsController.php#L265

Maybe this can be fixed by moving this logic to the `Event` element's `afterSave` method?

**Comment by gustavs-gutmanis** [comment]
#88 issue addresses this issue and has been fixed in c1a42baabe9d5137f097f871c5fd86e13bb74607

**Comment by gustavs-gutmanis** [comment]
This issue has been addressed and will be resolved in the upcoming version.
