### ISSUE TITLE
EventsService::EVENT_AFTER_SAVE does not fire after saving element via slideout

### ISSUE THREAD

**Issue by mikejpeters** [solspace/craft3-calendar#87]
**Describe the bug or issue you're experiencing**

`EventsService::EVENT_AFTER_SAVE` does not fire after saving element via slideout

**Steps to reproduce**

1. Add some code subscribing to `EventsService::EVENT_AFTER_SAVE` event as described in the [ docs](https://docs.solspace.com/craft/calendar/v3/developer/events.html#events-for-calendar-events)
2. Create a custom Calendar Events field and and add it to an entry type
3. Create/edit an entry and select an event
4. Double-click on the selected event
5. Make changes and press Save

**Expected behavior**

Subscription should fire.

**Craft & Plugin Info:**

- Craft Version: 3.7.23
- Calendar Version: 3.3.7
- Calendar Edition: PRO
- Fresh Install or Upgrade: Upgrade

**Additional context**

I think this is related to #86 because it's also tied to code that is only fired in the calendar event controller, but not in Craft's `elements/save-element` action.

Ideally I'd prefer to use the existing `Element` events, but I'm not sure if there is a reason your plugin provides it's own event? i.e.:

```php
use Solspace\Calendar\Elements\Event as EventElement;

Event::on(EventElement::class, EventElement::EVENT_AFTER_SAVE, function (ModelEvent $e) {
  /* @var $event EventElement*/
  $event = $e->sender;
```

**Comment by gustavs-gutmanis** [comment]
The event you'd want to use is perfectly good for using, it doesn't differ from the Craft's Element event apart from it containing the `::isNew()` method.
The event exists because it has been considered good practice to add such events, but it seems like it has become a relic of the past now.
