### ISSUE TITLE
Select dates are not saved until after `EVENT_AFTER_SAVE`

### ISSUE THREAD

**Issue by mikejpeters** [solspace/craft3-calendar#88]
**Describe the bug or issue you're experiencing**

We have custom code that subscribes to `EventsService::EVENT_AFTER_SAVE` and is intended to send an email about the new event, but `$event->getSelectDates()` is empty when creating an event that repeats on select days.

**Steps to reproduce**

1. Add some code subscribing to `EventsService::EVENT_AFTER_SAVE` event as described in the [ docs](https://docs.solspace.com/craft/calendar/v3/developer/events.html#events-for-calendar-events), and have it access `$event->getSelectDates()`
2. Make changes to an event so that it repeats on select dates and press Save

**Expected behavior**

`$event->getSelectDates()` in subscription should return selected dates.

**Craft & Plugin Info:**

- Craft Version: 3.7.23
- Calendar Version: 3.3.7
- Calendar Edition: PRO
- Fresh Install or Upgrade: Upgrade

**Additional context**

I believe the issue is here:

https://github.com/solspace/craft3-calendar/blob/e1108143e3d44e4de8544c3073996b8b27147285/packages/plugin/src/Controllers/EventsController.php#L255-L265

**Comment by kjmartens** [comment]
Hi @mikejpeters,

Sorry for the delay on this issue and the others. We're pivoting to Calendar today and will be investigating these issues. Thanks for the PR as well. 🙂

**Comment by gustavs-gutmanis** [comment]
Hi, @mikejpeters 

Thanks for the PR, I greatly appreciate it. I used it as reference to make some more changes, including saving the exception dates in the same manner as well. I'll be closing the PR, but the changes you made are in the commit that mentions this issue.

We will be pushing out a new version with these changes soon.

**Comment by kjmartens** [comment]
This should be fixed in v3.3.8 now. 🙂
