### ISSUE TITLE
Event queries

### ISSUE THREAD

**Issue by sebastian-lenz** [solspace/craft3-calendar#9]
This is a follow up issue regarding #4. Thanks for the update, I can see you've added some additional queries to the `EventQuery::beforePrepare` method.

However, using `rangeStart` and `rangeEnd` does not consider events that spawn multiple days. E.g. when specifying `rangeStart` as `today`, an event that has started yesterday and will last till tomorrow is excluded as the condition `startDate >= :rangeStart` (https://github.com/solspace/craft3-calendar/blob/master/src/Elements/Db/EventQuery.php#L494) is not met. Shouldn't the check be something like `endDate >= :rangeStart`? Again, it would be great if we could use custom operators to bypass this problems.

Also I wanted to note that the filtering of events using rrules looks suspicious to me. You ignore `startDate` if a rrule is present but on the `endDate` there is no such check. But even if an event has an rrule isn't its `startDate` always present but the `endDate` may vary? Furthermore, isn't the field `until` used to store the end date of the rrule result, so shouldn't that be used?

**Comment by kjmartens** [comment]
Thanks for reporting this, and thanks for the detail. :)

We'll have an update (beta 5) out today that will mostly fix this, but there will be some timezone issues you may notice that will be addressed in the next build of Calendar.
