### ISSUE TITLE
Export of recurring events not showing

### ISSUE THREAD

**Issue by SamLNL** [solspace/craft3-calendar#91]
**Describe the bug or issue you're experiencing**

I have simular issue as #74 but slightly different.
Some recurring events don't show up using the `craft.calendar.events` in twig.
I'm using twig to export the calendar data (https://www.biljoenbad.nl/fullcalendar-events). This data will be used by fullCalendar.

Weird thing is, it only occurs to some of my events. Some of the events have no problems at all.

**Steps to reproduce**

**Watch "Banenzwemmen 12:00 - 13:45"** 

I've this event:
![calendar-settings](https://user-images.githubusercontent.com/21331474/146380881-9a4534c6-ada9-4184-ae40-79dff5a90d5f.png)

As you can see, the event is showing up at 4 january. Still all good.
![calendar](https://user-images.githubusercontent.com/21331474/146379950-bc20bf59-38a5-4334-ad59-cfe0a1f2e415.png)

But when I export my events:

```
{% set calendarSection = craft.entries.section('calendarPrices').one() %}
{% set calendars = [] %}
{% if calendarSection.calendar1 | length %}
  {% set calendars = calendars | merge ([calendarSection.calendar1.handle]) %}
{% endif %}
{% if calendarSection.calendar2 | length %}
  {% set calendars = calendars | merge ([calendarSection.calendar2.handle]) %}
{% endif %}

{% set finalResources = [] %}

{% set events = craft.calendar.events({
  calendar: calendars,
  rangeStart: "2 months ago",
}).all() %}
{% for event in events %}
    {% set eventResource = {
      resourceId: event.calendarId,
      title: event.title,
      allDay: event.allDay == '0' ? 0 : 1,
      start: event.startDate | date ('Y-m-d H:i:s', timezone='UTC'),
      end: event.endDate | date ('Y-m-d H:i:s', timezone='UTC'),
    } %}

    {% if event.activitiesLink.getUrl() | length %}
      {%  set eventResource = eventResource | merge({url: event.activitiesLink.getUrl()}) %}
    {% endif %}

    {% set finalResources = finalResources | merge ([eventResource]) %}
{% endfor %}
{{ finalResources|json_encode|raw }}
```
Resulting to: https://www.biljoenbad.nl/fullcalendar-events

As you can see, this event is not appearing in the data:

![calendar-output](https://user-images.githubusercontent.com/21331474/146380788-6f33257e-9e76-4f11-8447-a5c446633772.png)

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.26
- Calendar Version: 3.3.7.1
- Calendar Edition: Pro
- Fresh Install or Upgrade: Fresh

**Comment by SamLNL** [comment]
I just found a solution for my problem.

I changed 

```
{% set events = craft.calendar.events({
  calendar: calendars,
  rangeStart: "2 months ago",
}).all() %}
```

to

```
{% set events = craft.calendar.events({
  calendar: calendars,
  rangeStart: "2 months ago",
  rangeEnd: "6 months"
}).all() %}
```

Adding a rangeEnd to the query seem to be a quick fix for me.
I would still consider this a bug to look into.

**Comment by kjmartens** [comment]
Hi @SamLNL,

Very sorry for the delay on this one. The export feature will assume the start/end dates are `today` when the `rangeStart` and `rangeEnd` parameters are not specified, rather than infinite for performance reasons. We always recommend adding these parameters and using a reasonable timeframe in them. 🙂
