### ISSUE TITLE
Undefined index: name

### ISSUE THREAD

**Issue by bfjare** [solspace/craft3-calendar#95]
"craftcms/cms": "3.7.30.1",

Upgrading calendar from 3.3.5 => 3.3.7

`yii\base\ErrorException: Undefined index: name

Migration: Solspace\Calendar\migrations\m210929_131016_PermissionsMigrationForProjectConfig

Output:

Exception: Undefined index: name (/Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/services/UserGroups.php:295)
#0 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/web/ErrorHandler.php(84): craft\web\ErrorHandler->handleError()
#1 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/services/UserGroups.php(295): craft\web\ErrorHandler->handleError()
#2 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1681): craft\services\UserGroups->handleChangedUserGroup()
#3 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/services/ProjectConfig.php(1190): craft\web\Application->craft\base\{closure:/Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/base/ApplicationTrait.php:1680-1682}()
#4 /Users/primeinc/Local Sites/riverside-2021/app/vendor/yiisoft/yii2/base/Component.php(633): craft\services\ProjectConfig->handleChangeEvent()
#5 /Users/primeinc/Local Sites/riverside-2021/app/vendor/yiisoft/yii2/base/Component.php(633): ::call_user_func:{/Users/primeinc/Local Sites/riverside-2021/app/vendor/yiisoft/yii2/base/Component.php:633}()
#6 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/services/ProjectConfig.php(753): craft\services\ProjectConfig->trigger()
#7 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/services/ProjectConfig.php(1180): craft\services\ProjectConfig->_processConfigChangesInternal()
#8 /Users/primeinc/Local Sites/riverside-2021/app/vendor/yiisoft/yii2/base/Component.php(633): craft\services\ProjectConfig->handleChangeEvent()
#9 /Users/primeinc/Local Sites/riverside-2021/app/vendor/yiisoft/yii2/base/Component.php(633): ::call_user_func:{/Users/primeinc/Local Sites/riverside-2021/app/vendor/yiisoft/yii2/base/Component.php:633}()
#10 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/services/ProjectConfig.php(753): craft\services\ProjectConfig->trigger()
#11 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/services/ProjectConfig.php(522): craft\services\ProjectConfig->_processConfigChangesInternal()
#12 /Users/primeinc/Local Sites/riverside-2021/app/vendor/solspace/craft3-calendar/packages/plugin/src/migrations/m210929_131016_PermissionsMigrationForProjectConfig.php(70): craft\services\ProjectConfig->set()
#13 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/db/Migration.php(52): Solspace\Calendar\migrations\m210929_131016_PermissionsMigrationForProjectConfig->safeUp()
#14 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/db/MigrationManager.php(232): Solspace\Calendar\migrations\m210929_131016_PermissionsMigrationForProjectConfig->up()
#15 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp()
#16 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/services/Updates.php(250): craft\db\MigrationManager->up()
#17 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(532): craft\services\Updates->runMigrations()
#18 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/controllers/UpdaterController.php(201): craft\controllers\UpdaterController->runMigrations()
#19 /Users/primeinc/Local Sites/riverside-2021/app/vendor/yiisoft/yii2/base/InlineAction.php(57): craft\controllers\UpdaterController->actionMigrate()
#20 /Users/primeinc/Local Sites/riverside-2021/app/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/Users/primeinc/Local Sites/riverside-2021/app/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#21 /Users/primeinc/Local Sites/riverside-2021/app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#22 /Users/primeinc/Local Sites/riverside-2021/app/vendor/yiisoft/yii2/base/Module.php(552): craft\controllers\UpdaterController->runAction()
#23 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/web/Application.php(287): craft\web\Application->runAction()
#24 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/web/Application.php(684): craft\web\Application->runAction()
#25 /Users/primeinc/Local Sites/riverside-2021/app/vendor/craftcms/cms/src/web/Application.php(244): craft\web\Application->_processUpdateLogic()
#26 /Users/primeinc/Local Sites/riverside-2021/app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#27 /Users/primeinc/Local Sites/riverside-2021/app/public/index.php(21): craft\web\Application->run()
#28 {main}`

**Comment by kjmartens** [comment]
Hi @bfjare, sorry about this issue you're experiencing. I'm not sure why this issue is happening exactly, but this migration should be fairly inconsequential and can be bypassed. What you can do is open up `/vendor/solspace/craft3-calendar/packages/plugin/src/migrations/m210929_131016_PermissionsMigrationForProjectConfig.php` and update it to just:

``` php
<?php

namespace Solspace\Calendar\migrations;

use Craft;
use craft\db\Migration;
use craft\db\Query;
use craft\db\Table;
use Solspace\Calendar\Calendar;

/**
 * m210929_131016_PermissionsMigrationForProjectConfig migration.
 */
class m210929_131016_PermissionsMigrationForProjectConfig extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m210929_131016_PermissionsMigrationForProjectConfig cannot be reverted.\n";

        return false;
    }
}
```

Then try the upgrade again. I would then be sure to resave any user group permissions (if you have any) after the upgrade.
